# Backend configuration for staging environment

bucket         = "terraform-state-webapp-stg"
key            = "applications/webapp/stg/terraform.tfstate"
region         = "us-east-1"
dynamodb_table = "terraform-state-lock-stg"
encrypt        = true

# Optional: Use specific AWS profile
# profile = "stg-profile"